name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  JAVA_VERSION: '25'
  JAVA_DISTRO: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v5

      - name: 'Set up Java'
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: 'Cache Maven packages'
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: 'Build'
        run: ./mvnw -B -ntp --file pom.xml verify
